Bind mount docker.sock to wait container to use `docker wait` and `docker cp`

diff --git a/Dockerfile-argoexec b/Dockerfile-argoexec
--- a/Dockerfile-argoexec
+++ b/Dockerfile-argoexec
@@ -1,12 +1,34 @@
 FROM debian:9.1
 
 RUN apt-get update && \
-    apt-get install -y curl jq procps git && \
+    apt-get install -y curl jq procps git tar && \
     rm -rf /var/lib/apt/lists/* && \
     curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
     chmod +x ./kubectl && \
     mv ./kubectl /bin/
 
+ENV DOCKER_CHANNEL edge
+ENV DOCKER_VERSION 17.10.0-ce
+# TODO ENV DOCKER_SHA256
+# https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
+# (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
+
+RUN set -ex; \
+    dockerArch='x86_64'; \
+	if ! curl -fL -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+		exit 1; \
+	fi; \
+	\
+	tar --extract \
+		--file docker.tgz \
+		--strip-components 1 \
+		--directory /usr/local/bin/ \
+	; \
+	rm docker.tgz; \
+	\
+	dockerd -v; \
+	docker -v
 
 COPY dist/argoexec /bin/
 
